
- name: generate keys
  hosts: all

  vars:
    key_location: /tmp/my-key

  tasks:
    - name: ensure age binary
      apt:
        name: age
        state: present

    - name: Ensure age key
      shell:
         age-keygen -o {{ key_location }}
      args:
        creates: '{{ key_location }}'

    - name: Fetch key to control machine
      fetch:
        src: '{{ key_location }}'
        dest: './keys/{{ inventory_hostname }}/keys.txt'
        flat: true

    - name: Load keys to fact
      set_fact:
        remote_key:
          "{{ lookup('file', './keys/' + inventory_hostname + '/keys.txt') }}"

