
- name: generate keys
  hosts: all

  vars:
    key_location: /tmp/my-key

  tasks:
    - name: ensure age binary
      apt:
        name: age
        state: present

    - name: Ensure age key
      shell:
         age-keygen -o {{ key_location }}
      args:
        creates: '{{ key_location }}'
