---
- name: Install NTPD and start it
  hosts: all

  tasks:
  - name: Install NTP
    apt: name=openntpd state=present

  - name: Provide config file
    copy:
      src: chrony.conf
      dest: /etc/openntpd.conf
    notify: 
       - Restart NTP

  - name: Start NTP
    service:
      name: openntpd
      state: started
      enabled: true

  handlers:
  - name: Restart NTP
    service:
      name: openntpd
      state: restarted

# TODO: show flush_handlers 
   
