---
- name: Install chrony and start it
  hosts: all

  tasks:
  - name: Install chrony
    yum: 
       name: chrony
       state: present

  - name: Provide config file
    copy:
      src: chrony.conf
      dest: /etc/chrony.conf
    notify: 
       - Restart chrony

  - name: Start Chrony
    service:
      name: chronyd
      state: started
      enabled: true

  handlers:
  - name: Restart chrony
    service:
       name: chronyd
       state: restarted

