---
- name: Create directories
  hosts: all
  user: root
  gather_facts: no

  tasks:
    - name: Create program diretories
      file:
        name: '{{item}}'
        state: directory
      loop: 
         - /etc/very-important
         - /var/lib/very-important
         - /var/cache/very-important
