---
- name: Install common packages
  hosts: all
  user: root
  gather_facts: no

  tasks:
    - name: Install packages
      package:
        state: present
        name: '{{ item }}'
      with_items: '{{ common_packages }}'
