---
- name: Slow tasks
  hosts: all
  user: root
  gather_facts: no
#  serial: 25%
#  max_fail_percentage: 50
#  any_errors_fatal: true

  tasks:
    - set_fact: 
         _random: "{{6|random}}"

    - assert: 
         that: '{{ _random|int > 1 }}'

    - debug: msg="I'm alive"
