---
- name: Show modifiers
  hosts: all
  user: root
  gather_facts: no

  tasks:
    - name: Do something
      shell: "cat /proc/loadavg"
      register: _loadavg
      changed_when: _loadavg.rc != 0
      failed_when: _loadavg.rc in [1,2]
      always_run: true
