- name: Show modifiers
  hosts: all
  user: root
  gather_facts: no

  tasks:
    - name: Get hostname
      command: hostname
      register: _result
      changed_when: false
      check_mode: false

    - set_fact:
        hostname: '{{ _result.stdout }}'

    - debug:
        msg: "My hostname is {{ hostname }}"
