---
- name: Create web directory
  hosts: all
  vars:
      target_dir: /var/www/magic

  tasks:
  - name: Create diretory
    file:
      path: '{{ target_dir }}'
      state: directory
    register: _made_directory

  - name: Create password
    shell: 
        ps ax | md5sum > {{ target_dir }}/password.txt
    when: _made_directory.changed

