---
- name: Setup webs
  hosts: all
  user: root
  gather_facts: no

  vars:
    mysites: 
       - www.root.cz
       - secure.root.cz
  tasks:
    - name: Setup web sites
      include_tasks: setup-one-web.yml
      loop: '{{ mysites }}'
