---
- name: NTP and start it
  hosts: all
  tasks:

  - include_tasks: setup-RedHat.yml 
    when: ansible_os_family == 'RedHat'

  - include_tasks: setup-Debian.yml 
    when: ansible_os_family == 'Debian'

