# 00-install-ntp.yml
---
- name: NTP and start it
  hosts: all
  tasks:

  - name: Handle RedHat NTP setup
    include_tasks: setup-RedHat.yml 
    when: ansible_os_family == 'RedHat'

  - name: Handle Debian NTP setup
    include_tasks: setup-Debian.yml 
    when: ansible_os_family == 'Debian'

